// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TransformCMYK_TextureFXKeys
    {
        public static readonly ValueParameterKey<Matrix> TransformC = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformM = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformY = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformK = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformA = ParameterKeys.NewValue<Matrix>();
    }
}
