// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TransformColorSpace_TextureFXKeys
    {
        public static readonly ValueParameterKey<Matrix> Transform0 = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> Transform1 = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> Transform2 = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> Transform3 = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<int> type = ParameterKeys.NewValue<int>();
    }
}
