// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class TransformRGBA_TextureFXKeys
    {
        public static readonly ValueParameterKey<Matrix> TransformR = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformG = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformB = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Matrix> TransformA = ParameterKeys.NewValue<Matrix>();
    }
}
