// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class H_PerlinKeys
    {
        public static readonly ObjectParameterKey<Texture> permTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> permTexture2d = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> permGradTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> gradTexture4d = ParameterKeys.NewObject<Texture>();
    }
}
