// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class ASCII_TextureFXKeys
    {
        public static readonly ValueParameterKey<bool> Grayscale = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<int> CharacterCount = ParameterKeys.NewValue<int>(176);
        public static readonly ValueParameterKey<Vector2> CharacterSize = ParameterKeys.NewValue<Vector2>(new Vector2(4.0f,6.0f));
        public static readonly ValueParameterKey<float> GridSize = ParameterKeys.NewValue<float>();
    }
}
