// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Simplex_Internal_TextureFXKeys
    {
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<int> frequencyCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> offsetCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> strengthCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<int> maxCount = ParameterKeys.NewValue<int>();
        public static readonly ValueParameterKey<Color4> BackgroundColor = ParameterKeys.NewValue<Color4>(new Color4(0.0f,0.0f,0.0f,1.0f));
        public static readonly ValueParameterKey<Color4> SimplexColor = ParameterKeys.NewValue<Color4>(new Color4(1.0f,1.0f,1.0f,1.0f));
        public static readonly ObjectParameterKey<Buffer> frequencyBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> offsetBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> strengthBuffer = ParameterKeys.NewObject<Buffer>();
    }
}
