// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class Stripes_TextureFXKeys
    {
        public static readonly ValueParameterKey<int> Tiling = ParameterKeys.NewValue<int>(10);
        public static readonly ValueParameterKey<bool> IsHorizontal = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> Offset = ParameterKeys.NewValue<float>(0);
        public static readonly ValueParameterKey<float> RandomSeed = ParameterKeys.NewValue<float>(0.33f);
    }
}
