// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class ThresholdKeys
    {
        public static readonly ValueParameterKey<Color4> ColorA = ParameterKeys.NewValue<Color4>(new Color4(0,0,0,1));
        public static readonly ValueParameterKey<Color4> ColorB = ParameterKeys.NewValue<Color4>(new Color4(1,1,1,1));
        public static readonly ValueParameterKey<float> Threshold = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> Smooth = ParameterKeys.NewValue<float>(0.02f);
        public static readonly ValueParameterKey<bool> Invert = ParameterKeys.NewValue<bool>();
        public static readonly ValueParameterKey<bool> AntiAliasing = ParameterKeys.NewValue<bool>();
    }
}
