// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class GrowthFlowPass0_TextureFXKeys
    {
        public static readonly ValueParameterKey<bool> Reset = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<bool> HideBrush = ParameterKeys.NewValue<bool>(false);
        public static readonly ValueParameterKey<float> Speed = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<float> Fade = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> EdgeWidth = ParameterKeys.NewValue<float>(2.0f);
        public static readonly ValueParameterKey<float> MapShape = ParameterKeys.NewValue<float>(2.0f);
    }
}
