// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class GodRays_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> Direction = ParameterKeys.NewValue<Vector2>(new Vector2(.50f,.50f));
        public static readonly ValueParameterKey<float> Density = ParameterKeys.NewValue<float>(0.35f);
        public static readonly ValueParameterKey<int> Samples = ParameterKeys.NewValue<int>(32);
        public static readonly ValueParameterKey<float> Weight = ParameterKeys.NewValue<float>(0.6f);
        public static readonly ValueParameterKey<float> Exposure = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> Decay = ParameterKeys.NewValue<float>(0.85f);
        public static readonly ValueParameterKey<Color4> Color = ParameterKeys.NewValue<Color4>(new Color4(1.0f,1.0f,1.0f,1.0f));
    }
}
