// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class SimulationKeys
    {
        public static readonly ValueParameterKey<uint> ParticlesCount = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<bool> Reset = ParameterKeys.NewValue<bool>();
        public static readonly ValueParameterKey<Vector3> TargetPos = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<float> TargetStrength = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Buffer> ParticlesBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> RandomValues = ParameterKeys.NewObject<Buffer>();
    }
}
