// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class LightMap_Internal_TextureFXKeys
    {
        public static readonly ValueParameterKey<Vector2> lightPos = ParameterKeys.NewValue<Vector2>();
        public static readonly ValueParameterKey<Vector2> lightSize = ParameterKeys.NewValue<Vector2>(new Vector2(1,1));
        public static readonly ValueParameterKey<float> shadowSoftness = ParameterKeys.NewValue<float>(1.0f);
        public static readonly ValueParameterKey<Color4> Color = ParameterKeys.NewValue<Color4>(new Color4(1,1,1,1));
        public static readonly ValueParameterKey<float> Gamma = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ValueParameterKey<float> THRESHOLD = ParameterKeys.NewValue<float>(0.75f);
    }
}
