// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class SimulationKeys
    {
        public static readonly ValueParameterKey<uint> ParticlesCount = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<bool> Reset = ParameterKeys.NewValue<bool>();
        public static readonly ValueParameterKey<Vector3> TargetPos = ParameterKeys.NewValue<Vector3>();
        public static readonly ValueParameterKey<float> TargetStrength = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Buffer> ParticlesBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> RandomValues = ParameterKeys.NewObject<Buffer>();
    }
}
