// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class RaymarchTestFloat4Keys
    {
        public static readonly ValueParameterKey<int> marchMaxIterations = ParameterKeys.NewValue<int>(120);
        public static readonly ValueParameterKey<float> marchMaxDistance = ParameterKeys.NewValue<float>(200);
        public static readonly ValueParameterKey<float> marchMinDistance = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> marchStepLength = ParameterKeys.NewValue<float>(0.75f);
        public static readonly ValueParameterKey<float> alpha = ParameterKeys.NewValue<float>(1);
    }
}
