// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Xenko.Rendering;
using SiliconStudio.Xenko.Graphics;
using SiliconStudio.Xenko.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Xenko.Graphics.Buffer;

namespace CustomParticlesTest
{
    internal static partial class ShaderMixins
    {
        internal partial class ParticlesDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "ParticlesDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("ParticlesDrawEffect", new ParticlesDrawEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class PointcloudDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "PointcloudDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("PointcloudDrawEffect", new PointcloudDrawEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class PointcloudTextureDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "PointcloudTextureDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("PointcloudTextureDrawEffect", new PointcloudTextureDrawEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class RingBufferDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "RingBufferDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("RingBufferDrawEffect", new RingBufferDrawEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class StreamsDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "StreamsDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("StreamsDrawEffect", new StreamsDrawEffect());
            }
        }
    }
}
