// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace CustomParticlesTest
{
    internal static partial class ShaderMixins
    {
        internal partial class TestStreamOutEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "TestStreamOut");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TestStreamOutEffect", new TestStreamOutEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class TestStreamOutDrawEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "TestStreamOutDraw");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("TestStreamOutDrawEffect", new TestStreamOutDrawEffect());
            }
        }
    }
    internal static partial class ShaderMixins
    {
        internal partial class InstanceNoodlesSplinesEffect  : IShaderMixinBuilder
        {
            public void Generate(ShaderMixinSource mixin, ShaderMixinContext context)
            {
                context.Mixin(mixin, "InstanceNoodlesSplines");
            }

            [ModuleInitializer]
            internal static void __Initialize__()

            {
                ShaderMixinManager.Register("InstanceNoodlesSplinesEffect", new InstanceNoodlesSplinesEffect());
            }
        }
    }
}
