// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class WarpTime_ComputeFXKeys
    {
        public static readonly ValueParameterKey<Vector2> Reso = ParameterKeys.NewValue<Vector2>(new Vector2(512.0f,512.0f));
        public static readonly ValueParameterKey<bool> Reset = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<float> Fade = ParameterKeys.NewValue<float>(0.5f);
        public static readonly ObjectParameterKey<Texture> TexCol = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Buffer> Out = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Texture> Tex3D = ParameterKeys.NewObject<Texture>();
    }
}
